language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"
jdk:
  - openjdk8
stages:
  - build
  - deploy
jobs:
  include:
    - stage: build
      script:
        - mvn clean && mvn package
        - if [ ! -z "$TRAVIS_TAG" ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
          docker build tidb-docker-compose-panel-web -t strrl/tidb-docker-compose-panel-web:latest -t strrl/tidb-docker-compose-panel-web:${TRAVIS_TAG} && \
          docker push strrl/tidb-docker-compose-panel-web:latest && \
          docker push strrl/tidb-docker-compose-panel-web:${TRAVIS_TAG};
          else
          docker build tidb-docker-compose-panel-web -t strrl/tidb-docker-compose-panel-web:beta && \
          docker push strrl/tidb-docker-compose-panel-web:beta;
          fi ;
