language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"
    - "tidb-docker-compose-panel-web-ui/node_modules"
    - "tidb-docker-compose-panel-web-ui/node"
jdk:
  - openjdk8
stages:
  - build
  - deploy
jobs:
  include:
    - stage: build
      script:
        - mvn clean && mvn package
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
        - if [ ! -z "$TRAVIS_TAG" ]; then
            docker build tidb-docker-compose-panel-web -t strrl/tidb-docker-compose-panel-web:latest -t strrl/tidb-docker-compose-panel-web:${TRAVIS_TAG};
            docker push strrl/tidb-docker-compose-panel-web:latest;
            docker push strrl/tidb-docker-compose-panel-web:${TRAVIS_TAG};
          else
            docker build tidb-docker-compose-panel-web -t strrl/tidb-docker-compose-panel-web:beta;
            docker push strrl/tidb-docker-compose-panel-web:beta;
          fi ;
    - stage: deply
      deploy:
        on:
          tags: true
        provider: releases
        skip_cleanup: true
        file:
          - "tidb-docker-compose-panel-web/target/tidb-docker-compose-panel-web-*-exec.jar"
          - "tidb-docker-compose-panel-cli/target/tidb-docker-compose-panel-cli-*-exec.jar"
        file_glob: true
        access_key_id: ${GITHUB_RELEASE_TOKEN}